### PR TITLE
Added price v2 beta into docs

### PR DESCRIPTION
**Pull request by wowmiir**
This PR contains the following changes:
1. added Price V2 (Beta) docs into Station

### CODE REVIEW

**Comment by 0xYankee-Raccoons** [comment]
Link in megamenu is broken, I think this is due to improper slug/url for the page itself? see images

Also, let's arrange the file location to the bottom of `Price API V1` instead of at the bottom?

Screenshot 2024-09-05 at 11 22 32
Screenshot 2024-09-05 at 11 22 14
Screenshot 2024-09-05 at 11 22 11

**Comment by 0xYankee-Raccoons** [comment]
`Making sense of data` and `extraInfo field` section should be in the API playground?

**Comment by Rustruff** [comment]
Screenshot 2024-09-05 at 12 06 56 PM
first line ids, maximum of 100 unique IDs allowed. not 10.

Screenshot 2024-09-05 at 12 08 57 PM
remove all contents from SS attached

**Comment by Rustruff** [comment]
> `Making sense of data` and `extraInfo field` section should be in the API playground?

at the moment, API playground does not have any /price endpoints. Moving forward, most of the APIs would be redirected towards api.jup.ag in a read.me style

Would it be the best practice to have `Making sense of data` and `extraInfo field section` within playground? Im unsure & open to it

**Pull request closed without merging**
