### PR TITLE
Correct min amount to be 500 and not 500k

### PR DESCRIPTION
**Pull request by melvinzhang**

### CODE REVIEW

**Comment by benlvb** [comment]
Are we reducing it to 500 for new dex / AMM?

**Comment by benlvb** [comment]
$500 seems a little too low for us to integrate any new DEX / AMM. What's the rational behind lowering it to $500 if I may ask.

**Comment by melvinzhang** [comment]
The subpoint below this one states "Each market/pool must have a minimum liquidity of $500 to show up on Jupiter." whereas the parent point states "Minimum DEX TVL of $500k"

One of them has to be a typo. I'm assuming the correct number is the one in the subpoint.

**Comment by benlvb** [comment]
I could phrase it better but the idea is that. 
Say BenDEX needs to have at least $500k in TVL as a whole project and for each market/ pool i.e. SOL-USDC pool within BenDEX needs to have at least $500 for Jupiter crawler to pick it up after we've integrated their DEX.

Does that make sense?

**Comment by melvinzhang** [comment]
Thanks for the clarification! I confused DEX TVL with the minimum liquidity per pool. My bad, there is no error so closing this.

**Pull request closed without merging**
