### PR TITLE
Add third party hosted API

### PR DESCRIPTION
**Pull request by zer0cache**
We hosted a free instance of [Metis - Jupiter V6 Swap API](https://marketplace.quicknode.com/add-on/metis-jupiter-v6-swap-api) that takes a 0.2% platform fee on swaps for those that aren't willing to self host, yet run into rate limit or latency issues with `https://quote-api.jup.ag/v6`.

It offers:
- Up to 50 requests/sec
- 80ms Latency or faster
- Hosted in Ashburn, Virginia (US East region) for those that want to co-locate in order to reduce latency

More information can be found at [https://www.jupiterapi.com/](https://www.jupiterapi.com/)

### CODE REVIEW

**Comment by abunsen** [comment]
smol bump

**Comment by abunsen** [comment]
lil bump

**Comment by abunsen** [comment]
micro bump

**Comment by 9yoi** [comment]
The use of jupiterapi.com is misleading, please use your own unique domain name.

**Pull request closed without merging**
